M48
; DRILL file {KiCad (6.0.8)} date Mon Jul 24 16:34:00 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-24T16:34:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X96.55Y-45.7
X111.55Y-45.7
T2
X96.55Y-36.9
X111.55Y-36.9
T0
M30
